" Sources: 
"     https://vim.fandom.com/wiki/Example_vimrc
"     https://dougblack.io/words/a-good-vimrc.html
"     https://github.com/amix/vimrc/blob/master/vimrcs/basic.vim
"     https://chrisyeh96.github.io/2017/12/18/vimrc.html

" TODO: Check https://github.com/amix/vimrc more
 
" Colorscheme
colorscheme koehler

" Enable syntax highlighting
syntax on

" Set encoding to UTF-8
set encoding=utf-8

" Show line numbers
set number

" Show file stats
set ruler

" Better command-line completion
set wildmenu

" Redraw screen only when we need to
set lazyredraw
 
" Show partial commands in the last line of the screen
set showcmd

" Highlight current line
set cursorline

" Configure Vim to use brighter colors
set background=dark

" Autoreload the file in Vim if it has been changed outside of Vim
set autoread

" Highlight matching [{()}]
set showmatch
 
" Highlight searches
set hlsearch

" Ignore case when searching
set ignorecase

" Search as characters are entered
set incsearch

" Use case insensitive search, except when using capital letters
set smartcase

" Display the cursor position on the last line of the screen or in the status line of a window
set ruler
 
" Always display the status line, even if only one window is displayed
set laststatus=2

" Format the status line
set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l\ \ Column:\ %c

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Enable use of the mouse for all modes
set mouse=a

set tabstop=4
set softtabstop=4

" Be smart when using tabs
set smarttab

" Delete trailing white space on save, useful for some filetypes
fun! CleanExtraSpaces()
    let save_cursor = getpos(".")
    let old_query = getreg('/')
    silent! %s/\s\+$//e
    call setpos('.', save_cursor)
    call setreg('/', old_query)
endfun

if has("autocmd")
    autocmd BufWritePre *.txt,*.js,*.py,*.wiki,*.sh,*.coffee :call CleanExtraSpaces()
endif

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Helper functions
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Returns true if paste mode is enabled
function! HasPaste()
    if &paste
        return 'PASTE MODE  '
    endif
    return ''
endfunction
