network:
  version: 2
  ethernets:
    ens160:
      addresses:
      - 192.168.21.72/24
      nameservers:
        addresses:
        - 192.168.21.254
        search: []
      routes:
      - to: default
        via: 192.168.21.1
